# /*******************************************************
* Copyright         : 2022 Vaibhav Khandare
* Description       : Supervised :- This file predict the chances of pass and fail of student using study hours 
*                    
* Revision History  :
* 		Author 		
        Vaibhav Khandare 
* ------------------------------------------------------------------
/******************************************************************/

In [1]:
import pandas as pd

In [2]:
db = pd.read_csv('Book1.csv')

In [3]:
db

name   hours  marks
0  Vaibhav      8     80
1    Krish      6     60
2   Sachin      4     40
3    Pavan      2     20

In [4]:
y = db['marks']

In [23]:
y

0    80
1    60
2    40
3    20
Name: marks, dtype: int64

In [24]:
x = db['hours']

In [25]:
x

0    8
1    6
2    4
3    2
Name: hours, dtype: int64

In [26]:
x.shape

(4,)

In [27]:
type(x)

pandas.core.series.Series

In [28]:
#to convert pandas into numpy 
x = x.values

In [29]:
type(x)

numpy.ndarray

In [30]:
x.reshape(4,1)

array([[8],
       [6],
       [4],
       [2]], dtype=int64)

In [31]:
x.reshape(1,4)

array([[8, 6, 4, 2]], dtype=int64)

In [32]:
x = x.reshape(-1,1)

In [33]:
x.shape

(4, 1)

In [34]:
x

array([[8],
       [6],
       [4],
       [2]], dtype=int64)

In [35]:
from sklearn.linear_model import LinearRegression

mind = LinearRegression()

In [36]:
mind = LinearRegression()

In [38]:
#exp: model: linear function
#w : weight/coeficient
#model trained
mind.fit(x,y)

LinearRegression()

In [39]:
mind.predict([[7]])

array([70.])

In [40]:
mind.predict([[5]])

array([50.])

In [41]:
#linear function : y= wx
# w=10
mind.coef_

array([10.])

In [42]:
import joblib

In [43]:
joblib.dump(mind,'Book1.pk1')

['Book1.pk1']

In [3]:
import pandas as pd 
db = pd.read_csv("salary.csv")
x = db ["YearsExperience"]
y = db ["Salary"]
x = x.values
x = x.reshape(30,1)
from sklearn.linear_model import LinearRegression 
mind = LinearRegression()
mind.fit(x,y)
b= float(input("Enter your Experiance here : "))
a = mind.predict([[b]])
a = print("Accordicng to your Experiance your Salary is : ",a)

Enter your Experiance here : 10
Accordicng to your Experiance your Salary is :  [120291.82341322]
