In [1]:
import pandas as pd
db = pd.read_csv('50_Startups.csv')

In [2]:
db.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [4]:
# To get all columns
db.columns


Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [5]:
# We have to preprocess this state feature
state = db['State']

In [6]:
# Importing LabelEncoder to do LabelEncoding 
from sklearn.preprocessing import LabelEncoder

In [7]:
#we make one variable state label encoding(le) and in that we store  LabelEncoder
state_le = LabelEncoder()

In [8]:
state_le

LabelEncoder()

In [9]:
#here in state_le_final variable we stored 0,1,2 no by transform string into no call label encoding
state_le_final = state_le.fit_transform(state)


In [10]:
# 0= california, 2= NewYark, 1= Florida
state_le_final

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2,
       1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2,
       0, 2, 1, 0, 2, 0])

In [11]:
#it gives array of type so here (50,) means 1D array
state_le_final.shape

(50,)

In [12]:
#it converts 1D array into 2D
state_le_final=state_le_final.reshape(-1,1)

In [13]:
#(50,1) mean 2D Arrays having 50 Rows and 1 Column
state_le_final.shape

(50, 1)

In [14]:
state_le_final

array([[2],
       [0],
       [1],
       [2],
       [1],
       [2],
       [0],
       [1],
       [2],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [2],
       [0],
       [2],
       [1],
       [2],
       [0],
       [2],
       [1],
       [1],
       [2],
       [0],
       [1],
       [2],
       [1],
       [2],
       [1],
       [2],
       [0],
       [1],
       [0],
       [2],
       [1],
       [0],
       [2],
       [0],
       [0],
       [1],
       [0],
       [2],
       [0],
       [2],
       [1],
       [0],
       [2],
       [0]])

One Hot Encoding gives 3d array and if city is there then gives 1 in that array like in label-encoding 
I put 2 as NewYark so one hot encoding gives [0,0,1] and for Florida i put in le 1 so ohe [0,1,0] 

In [15]:
# Now we have to do One Hot Encodin create dummy variable
from sklearn.preprocessing import OneHotEncoder

In [16]:
state_ohe = OneHotEncoder()

In [17]:
# we fit and tranformed the state_le_final using onehotEncoding and store it in one dummy variable state_ohe_final
state_ohe_final = state_ohe.fit_transform(state_le_final)

In [18]:
state_ohe_final

<50x3 sparse matrix of type '<class 'numpy.float64'>'
	with 50 stored elements in Compressed Sparse Row format>

In [19]:
state_final = state_ohe_final.toarray()

In [20]:
state_final

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0

In [21]:
# Now, we have to remove dependencies among feature i.e come out of Dummy Variable Trap 
# So, we have to remove any one coloumn. 
state_final_trap = state_final[:,0:2] 
# array[no. of rows : no of columns ]  we can apply slicing concept here. 
#[:,0:2] in this 1st (:) denotes no row do eliminate and for column 2nd (0:2) denotes start from 0 till 1 mean excluding 2 

In [22]:
state_final_trap

array([[0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [23]:
y = db['Profit']

In [24]:
X = db[ ["R&D Spend", "Administration", "Marketing Spend"] ]

In [25]:
X.head(5)

R&D Spend  Administration  Marketing Spend
0  165349.20       136897.80        471784.10
1  162597.70       151377.59        443898.53
2  153441.51       101145.55        407934.54
3  144372.41       118671.85        383199.62
4  142107.34        91391.77        366168.42

In [26]:
# We need to add state also in the features. We want to append horizontally 
import numpy
X = numpy.hstack((X,state_final_trap))

In [ ]:
X

In [ ]:
# this data is big so can split it for training and testing 
from sklearn.model_selection import train_test_split

In [ ]:
# Training & Testing split 
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2,random_state=42)

In [ ]:
# to check shape of training data
X_train.shape

In [ ]:
X_test.shape

In [ ]:
y_train.shape

In [ ]:
y_test.shape

In [ ]:
# Model 
from sklearn.linear_model import LinearRegression

In [ ]:
mind =  LinearRegression()

In [ ]:
mind

In [ ]:
mind.fit(X_train, y_train)

In [ ]:
# Weight of each feature
# Now looking at this weight we can find max weight is of R&D Spend i.e around 8. 
#So, if increase 1unit on R&D it increase profit by 8 times.
mind.coef_

In [ ]:
mind.predict(X_train)

In [ ]:
# to know beacause prediction requires numpy array not pandas so to convert pandas into numpy 
# .values is used but here we earlier convert to arrray
type(X_train)

In [ ]:
mind.predict(X_test)

In [ ]:
type(X_test)

In [ ]:
type(y_test)

In [ ]:
#to convert pandas into numpy 
y_test = y_test.values

In [ ]:
type(y_test)

In [ ]:
y_test = y_test.reshape(-1,1)

In [ ]:
y_test.shape