In [71]:
import pandas as pd

In [72]:
db = pd.read_csv("salary.csv")

In [73]:
db

YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [74]:
x = db['YearsExperience']

In [75]:
y = db['Salary']

In [76]:
x.shape

(30,)

In [77]:
type(x)

pandas.core.series.Series

In [115]:
x=x.values

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [79]:
type(x)

numpy.ndarray

In [80]:
x = x.reshape(30,1)

In [81]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [82]:
from sklearn.linear_model import LinearRegression

In [83]:
mind = LinearRegression()

In [84]:
mind.fit(x, y)

LinearRegression()

In [85]:
mind.predict([[4.2]])

array([65482.04194878])

In [86]:
#to find Accuracy
54142.0872/60150*100

90.0117825436409

In [87]:
mind.coef_

array([9449.96232146])

In [88]:
#to train and test the data
from sklearn.model_selection import train_test_split

In [89]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [90]:
x_train.shape

(24, 1)

In [91]:
x_test.shape

(6, 1)

In [92]:
y_train.shape

(24,)

In [93]:
y_test.shape

(6,)

In [94]:
mind.fit(x_train,y_train)

LinearRegression()

In [95]:
y_test

27    112635
15     67938
23    113812
17     83088
8      64445
9      57189
Name: Salary, dtype: int64

In [96]:
y_train

28    122391
24    109431
12     56957
0      39343
4      39891
16     66029
5      56642
13     57081
11     55794
22    101302
1      46205
2      37731
25    105582
3      43525
21     98273
26    116969
18     81363
29    121872
20     91738
7      54445
10     63218
14     61111
19     93940
6      60150
Name: Salary, dtype: int64

In [97]:
x_test

array([[9.6],
       [4.9],
       [8.2],
       [5.3],
       [3.2],
       [3.7]])

In [98]:
x_train

array([[10.3],
       [ 8.7],
       [ 4. ],
       [ 1.1],
       [ 2.2],
       [ 5.1],
       [ 2.9],
       [ 4.1],
       [ 4. ],
       [ 7.9],
       [ 1.3],
       [ 1.5],
       [ 9. ],
       [ 2. ],
       [ 7.1],
       [ 9.5],
       [ 5.9],
       [10.5],
       [ 6.8],
       [ 3.2],
       [ 3.9],
       [ 4.5],
       [ 6. ],
       [ 3. ]])

In [99]:
mind.predict(x_test)

array([115790.21011287,  71498.27809463, 102596.86866063,  75267.80422384,
        55477.79204548,  60189.69970699])

In [100]:
#accuracy at experiance 9.6 predicted and actual
112635/115814*100

97.25508142366208

In [101]:
y_train.shape

(24,)

In [102]:
type(y_train)

pandas.core.series.Series

In [103]:
y_train=y_train.values

In [104]:
type(y_train)

numpy.ndarray

In [105]:
#because the model require 2d array so we reshaped it
y_train = y_train.reshape(24,1)

In [106]:
mind.predict(y_train)

array([1.15341550e+09, 1.03128286e+09, 5.36777571e+08, 3.70786488e+08,
       3.75950739e+08, 6.22270424e+08, 5.33809069e+08, 5.37946124e+08,
       5.25817674e+08, 9.54676661e+08, 4.35452709e+08, 3.55595298e+08,
       9.95010591e+08, 4.10196884e+08, 9.26131925e+08, 1.10231958e+09,
       7.66775208e+08, 1.14852454e+09, 8.64547292e+08, 5.13104947e+08,
       5.95780079e+08, 5.75924100e+08, 8.85298533e+08, 5.66867813e+08])

In [107]:
y_test.shape

(6,)

In [108]:
type(y_test)

pandas.core.series.Series

In [109]:
#to convert pandas into numpy we require .values function
y_test = y_test.values

In [110]:
y_test

array([112635,  67938, 113812,  83088,  64445,  57189], dtype=int64)

In [111]:
type(y_test)

numpy.ndarray

In [112]:
y_test = y_test.reshape(6,1)

In [113]:
y_test

array([[112635],
       [ 67938],
       [113812],
       [ 83088],
       [ 64445],
       [ 57189]], dtype=int64)

In [114]:
mind.predict(y_test)

array([1.06147676e+09, 6.40260487e+08, 1.07256859e+09, 7.83031289e+08,
       6.07343100e+08, 5.38963896e+08])

In [65]:
mind.predict([[4.2]])

array([64901.60736851])